// Tabela CID-10 (exemplos - em produção, importar tabela completa)

export interface CID10 {
  codigo: string;
  descricao: string;
  categoria: string;
}

export const cid10Table: CID10[] = [
  { codigo: 'A00', descricao: 'Cólera', categoria: 'Doenças Infecciosas' },
  { codigo: 'A01', descricao: 'Febres tifóide e paratifóide', categoria: 'Doenças Infecciosas' },
  { codigo: 'A02', descricao: 'Outras infecções por Salmonella', categoria: 'Doenças Infecciosas' },
  { codigo: 'A03', descricao: 'Shiguelose', categoria: 'Doenças Infecciosas' },
  { codigo: 'A04', descricao: 'Outras infecções intestinais bacterianas', categoria: 'Doenças Infecciosas' },
  { codigo: 'A09', descricao: 'Diarréia e gastroenterite de origem infecciosa presumível', categoria: 'Doenças Infecciosas' },
  { codigo: 'B00', descricao: 'Infecções pelo vírus do herpes', categoria: 'Doenças Infecciosas' },
  { codigo: 'B01', descricao: 'Varicela', categoria: 'Doenças Infecciosas' },
  { codigo: 'B02', descricao: 'Herpes zoster', categoria: 'Doenças Infecciosas' },
  { codigo: 'B15', descricao: 'Hepatite A', categoria: 'Doenças Infecciosas' },
  { codigo: 'B16', descricao: 'Hepatite B aguda', categoria: 'Doenças Infecciosas' },
  { codigo: 'B17', descricao: 'Outras hepatites virais agudas', categoria: 'Doenças Infecciosas' },
  { codigo: 'B18', descricao: 'Hepatite viral crônica', categoria: 'Doenças Infecciosas' },
  { codigo: 'C00', descricao: 'Neoplasia maligna do lábio', categoria: 'Neoplasias' },
  { codigo: 'C10', descricao: 'Neoplasia maligna da orofaringe', categoria: 'Neoplasias' },
  { codigo: 'C15', descricao: 'Neoplasia maligna do esôfago', categoria: 'Neoplasias' },
  { codigo: 'C16', descricao: 'Neoplasia maligna do estômago', categoria: 'Neoplasias' },
  { codigo: 'C18', descricao: 'Neoplasia maligna do cólon', categoria: 'Neoplasias' },
  { codigo: 'C20', descricao: 'Neoplasia maligna do reto', categoria: 'Neoplasias' },
  { codigo: 'C25', descricao: 'Neoplasia maligna do pâncreas', categoria: 'Neoplasias' },
  { codigo: 'C34', descricao: 'Neoplasia maligna dos brônquios e dos pulmões', categoria: 'Neoplasias' },
  { codigo: 'C50', descricao: 'Neoplasia maligna da mama', categoria: 'Neoplasias' },
  { codigo: 'C53', descricao: 'Neoplasia maligna do colo do útero', categoria: 'Neoplasias' },
  { codigo: 'C61', descricao: 'Neoplasia maligna da próstata', categoria: 'Neoplasias' },
  { codigo: 'C78', descricao: 'Neoplasias malignas secundárias dos órgãos respiratórios e digestivos', categoria: 'Neoplasias' },
  { codigo: 'D50', descricao: 'Anemia por deficiência de ferro', categoria: 'Doenças do Sangue' },
  { codigo: 'D51', descricao: 'Anemia por deficiência de vitamina B12', categoria: 'Doenças do Sangue' },
  { codigo: 'D52', descricao: 'Anemia por deficiência de folato', categoria: 'Doenças do Sangue' },
  { codigo: 'D64', descricao: 'Outras anemias', categoria: 'Doenças do Sangue' },
  { codigo: 'E10', descricao: 'Diabetes mellitus insulino-dependente', categoria: 'Doenças Endócrinas' },
  { codigo: 'E11', descricao: 'Diabetes mellitus não-insulino-dependente', categoria: 'Doenças Endócrinas' },
  { codigo: 'E14', descricao: 'Diabetes mellitus não especificado', categoria: 'Doenças Endócrinas' },
  { codigo: 'E66', descricao: 'Obesidade', categoria: 'Doenças Endócrinas' },
  { codigo: 'E78', descricao: 'Distúrbios do metabolismo de lipoproteínas', categoria: 'Doenças Endócrinas' },
  { codigo: 'F10', descricao: 'Transtornos mentais e comportamentais devidos ao uso de álcool', categoria: 'Transtornos Mentais' },
  { codigo: 'F20', descricao: 'Esquizofrenia', categoria: 'Transtornos Mentais' },
  { codigo: 'F32', descricao: 'Episódios depressivos', categoria: 'Transtornos Mentais' },
  { codigo: 'F41', descricao: 'Outros transtornos de ansiedade', categoria: 'Transtornos Mentais' },
  { codigo: 'F43', descricao: 'Reações ao stress grave e transtornos de adaptação', categoria: 'Transtornos Mentais' },
  { codigo: 'G40', descricao: 'Epilepsia', categoria: 'Doenças do Sistema Nervoso' },
  { codigo: 'G43', descricao: 'Enxaqueca', categoria: 'Doenças do Sistema Nervoso' },
  { codigo: 'G44', descricao: 'Outras síndromes de algias cefálicas', categoria: 'Doenças do Sistema Nervoso' },
  { codigo: 'G93', descricao: 'Outros transtornos do encéfalo', categoria: 'Doenças do Sistema Nervoso' },
  { codigo: 'H10', descricao: 'Conjuntivite', categoria: 'Doenças dos Olhos' },
  { codigo: 'H25', descricao: 'Catarata senil', categoria: 'Doenças dos Olhos' },
  { codigo: 'H40', descricao: 'Glaucoma', categoria: 'Doenças dos Olhos' },
  { codigo: 'H52', descricao: 'Transtornos da refração e da acomodação', categoria: 'Doenças dos Olhos' },
  { codigo: 'H90', descricao: 'Perda de audição condutiva e neurossensorial', categoria: 'Doenças dos Ouvidos' },
  { codigo: 'I10', descricao: 'Hipertensão essencial (primária)', categoria: 'Doenças Circulatórias' },
  { codigo: 'I11', descricao: 'Doença cardíaca hipertensiva', categoria: 'Doenças Circulatórias' },
  { codigo: 'I20', descricao: 'Angina pectoris', categoria: 'Doenças Circulatórias' },
  { codigo: 'I21', descricao: 'Infarto agudo do miocárdio', categoria: 'Doenças Circulatórias' },
  { codigo: 'I25', descricao: 'Doença isquêmica crônica do coração', categoria: 'Doenças Circulatórias' },
  { codigo: 'I50', descricao: 'Insuficiência cardíaca', categoria: 'Doenças Circulatórias' },
  { codigo: 'I63', descricao: 'Infarto cerebral', categoria: 'Doenças Circulatórias' },
  { codigo: 'I64', descricao: 'Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico', categoria: 'Doenças Circulatórias' },
  { codigo: 'J00', descricao: 'Nasofaringite aguda (resfriado comum)', categoria: 'Doenças Respiratórias' },
  { codigo: 'J01', descricao: 'Sinusite aguda', categoria: 'Doenças Respiratórias' },
  { codigo: 'J02', descricao: 'Faringite aguda', categoria: 'Doenças Respiratórias' },
  { codigo: 'J03', descricao: 'Amigdalite aguda', categoria: 'Doenças Respiratórias' },
  { codigo: 'J04', descricao: 'Laringite e traqueíte agudas', categoria: 'Doenças Respiratórias' },
  { codigo: 'J06', descricao: 'Infecções agudas das vias aéreas superiores, de localizações múltiplas e não especificadas', categoria: 'Doenças Respiratórias' },
  { codigo: 'J10', descricao: 'Influenza devida a vírus da influenza identificado', categoria: 'Doenças Respiratórias' },
  { codigo: 'J11', descricao: 'Influenza devida a vírus não identificado', categoria: 'Doenças Respiratórias' },
  { codigo: 'J12', descricao: 'Pneumonia viral não classificada em outra parte', categoria: 'Doenças Respiratórias' },
  { codigo: 'J13', descricao: 'Pneumonia devida a Streptococcus pneumoniae', categoria: 'Doenças Respiratórias' },
  { codigo: 'J14', descricao: 'Pneumonia devida a Haemophilus influenzae', categoria: 'Doenças Respiratórias' },
  { codigo: 'J15', descricao: 'Pneumonia bacteriana não classificada em outra parte', categoria: 'Doenças Respiratórias' },
  { codigo: 'J18', descricao: 'Pneumonia por microorganismo não especificado', categoria: 'Doenças Respiratórias' },
  { codigo: 'J20', descricao: 'Bronquite aguda', categoria: 'Doenças Respiratórias' },
  { codigo: 'J40', descricao: 'Bronquite não especificada como aguda ou crônica', categoria: 'Doenças Respiratórias' },
  { codigo: 'J41', descricao: 'Bronquite crônica simples e mucopurulenta', categoria: 'Doenças Respiratórias' },
  { codigo: 'J44', descricao: 'Outras doenças pulmonares obstrutivas crônicas', categoria: 'Doenças Respiratórias' },
  { codigo: 'J45', descricao: 'Asma', categoria: 'Doenças Respiratórias' },
  { codigo: 'J96', descricao: 'Insuficiência respiratória não classificada em outra parte', categoria: 'Doenças Respiratórias' },
  { codigo: 'K21', descricao: 'Doença do refluxo gastroesofágico', categoria: 'Doenças Digestivas' },
  { codigo: 'K25', descricao: 'Úlcera gástrica', categoria: 'Doenças Digestivas' },
  { codigo: 'K26', descricao: 'Úlcera duodenal', categoria: 'Doenças Digestivas' },
  { codigo: 'K29', descricao: 'Gastrite e duodenite', categoria: 'Doenças Digestivas' },
  { codigo: 'K35', descricao: 'Apendicite aguda', categoria: 'Doenças Digestivas' },
  { codigo: 'K40', descricao: 'Hérnia inguinal', categoria: 'Doenças Digestivas' },
  { codigo: 'K59', descricao: 'Outros transtornos funcionais do intestino', categoria: 'Doenças Digestivas' },
  { codigo: 'K80', descricao: 'Colelitíase', categoria: 'Doenças Digestivas' },
  { codigo: 'K81', descricao: 'Colecistite', categoria: 'Doenças Digestivas' },
  { codigo: 'K92', descricao: 'Outras doenças do aparelho digestivo', categoria: 'Doenças Digestivas' },
  { codigo: 'L00', descricao: 'Síndrome da pele escaldada estafilocócica', categoria: 'Doenças da Pele' },
  { codigo: 'L20', descricao: 'Dermatite atópica', categoria: 'Doenças da Pele' },
  { codigo: 'L23', descricao: 'Dermatite alérgica de contato', categoria: 'Doenças da Pele' },
  { codigo: 'L30', descricao: 'Dermatite não especificada', categoria: 'Doenças da Pele' },
  { codigo: 'L40', descricao: 'Psoríase', categoria: 'Doenças da Pele' },
  { codigo: 'L50', descricao: 'Urticária', categoria: 'Doenças da Pele' },
  { codigo: 'L70', descricao: 'Acne', categoria: 'Doenças da Pele' },
  { codigo: 'L71', descricao: 'Rosácea', categoria: 'Doenças da Pele' },
  { codigo: 'L72', descricao: 'Cisto folicular da pele e do tecido subcutâneo', categoria: 'Doenças da Pele' },
  { codigo: 'L73', descricao: 'Outras afecções foliculares', categoria: 'Doenças da Pele' },
  { codigo: 'L98', descricao: 'Outras afecções da pele e do tecido subcutâneo não classificadas em outra parte', categoria: 'Doenças da Pele' },
  { codigo: 'M00', descricao: 'Artrite piogênica', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M05', descricao: 'Artrite reumatóide soropositiva', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M06', descricao: 'Outras artrites reumatóides', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M15', descricao: 'Poliartrose', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M19', descricao: 'Artrose não especificada', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M25', descricao: 'Outros transtornos articulares não classificados em outra parte', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M54', descricao: 'Dor dorsalgia', categoria: 'Doenças Osteomusculares' },
  { codigo: 'M79', descricao: 'Outros transtornos dos tecidos moles não classificados em outra parte', categoria: 'Doenças Osteomusculares' },
  { codigo: 'N00', descricao: 'Síndrome nefrítica aguda', categoria: 'Doenças Urogenitais' },
  { codigo: 'N10', descricao: 'Nefrite túbulo-intersticial aguda', categoria: 'Doenças Urogenitais' },
  { codigo: 'N18', descricao: 'Doença renal crônica', categoria: 'Doenças Urogenitais' },
  { codigo: 'N20', descricao: 'Cálculo do rim e do ureter', categoria: 'Doenças Urogenitais' },
  { codigo: 'N30', descricao: 'Cistite', categoria: 'Doenças Urogenitais' },
  { codigo: 'N40', descricao: 'Hiperplasia da próstata', categoria: 'Doenças Urogenitais' },
  { codigo: 'N70', descricao: 'Doença inflamatória da pelve feminina', categoria: 'Doenças Urogenitais' },
  { codigo: 'N76', descricao: 'Outras afecções inflamatórias da vagina e da vulva', categoria: 'Doenças Urogenitais' },
  { codigo: 'O00', descricao: 'Gravidez ectópica', categoria: 'Gravidez e Parto' },
  { codigo: 'O10', descricao: 'Hipertensão pré-existente complicando a gravidez, o parto e o puerpério', categoria: 'Gravidez e Parto' },
  { codigo: 'O16', descricao: 'Hipertensão materna não especificada', categoria: 'Gravidez e Parto' },
  { codigo: 'O21', descricao: 'Vômitos excessivos na gravidez', categoria: 'Gravidez e Parto' },
  { codigo: 'O36', descricao: 'Cuidados maternos por outros problemas fetais conhecidos ou suspeitos', categoria: 'Gravidez e Parto' },
  { codigo: 'O80', descricao: 'Parto único espontâneo', categoria: 'Gravidez e Parto' },
  { codigo: 'O82', descricao: 'Parto único por cesariana', categoria: 'Gravidez e Parto' },
  { codigo: 'R00', descricao: 'Anormalidades do batimento cardíaco', categoria: 'Sintomas Gerais' },
  { codigo: 'R05', descricao: 'Tosse', categoria: 'Sintomas Gerais' },
  { codigo: 'R06', descricao: 'Anormalidades da respiração', categoria: 'Sintomas Gerais' },
  { codigo: 'R10', descricao: 'Dor abdominal e pélvica', categoria: 'Sintomas Gerais' },
  { codigo: 'R50', descricao: 'Febre de origem desconhecida', categoria: 'Sintomas Gerais' },
  { codigo: 'R51', descricao: 'Cefaléia', categoria: 'Sintomas Gerais' },
  { codigo: 'R52', descricao: 'Dor não classificada em outra parte', categoria: 'Sintomas Gerais' },
  { codigo: 'R53', descricao: 'Mal-estar e fadiga', categoria: 'Sintomas Gerais' },
  { codigo: 'R55', descricao: 'Síncope e colapso', categoria: 'Sintomas Gerais' },
  { codigo: 'S00', descricao: 'Traumatismo superficial da cabeça', categoria: 'Traumatismos' },
  { codigo: 'S10', descricao: 'Traumatismo superficial do pescoço', categoria: 'Traumatismos' },
  { codigo: 'S20', descricao: 'Traumatismo superficial do tórax', categoria: 'Traumatismos' },
  { codigo: 'S30', descricao: 'Traumatismo superficial do abdome, do dorso e da pelve', categoria: 'Traumatismos' },
  { codigo: 'S40', descricao: 'Traumatismo superficial do ombro e do braço', categoria: 'Traumatismos' },
  { codigo: 'S50', descricao: 'Traumatismo superficial do cotovelo e do antebraço', categoria: 'Traumatismos' },
  { codigo: 'S60', descricao: 'Traumatismo superficial do punho e da mão', categoria: 'Traumatismos' },
  { codigo: 'S70', descricao: 'Traumatismo superficial do quadril e da coxa', categoria: 'Traumatismos' },
  { codigo: 'S80', descricao: 'Traumatismo superficial da perna', categoria: 'Traumatismos' },
  { codigo: 'S90', descricao: 'Traumatismo superficial do tornozelo e do pé', categoria: 'Traumatismos' },
  { codigo: 'T36', descricao: 'Envenenamento por antibióticos sistêmicos', categoria: 'Envenenamentos' },
  { codigo: 'T37', descricao: 'Envenenamento por outros agentes antiinfecciosos e antiparasitários sistêmicos', categoria: 'Envenenamentos' },
  { codigo: 'T38', descricao: 'Envenenamento por hormônios e seus substitutos sintéticos e antagonistas', categoria: 'Envenenamentos' },
  { codigo: 'T39', descricao: 'Envenenamento por analgésicos, antipiréticos e anti-reumáticos não-opiáceos', categoria: 'Envenenamentos' },
  { codigo: 'T40', descricao: 'Envenenamento por narcóticos e psicodislépticos', categoria: 'Envenenamentos' },
  { codigo: 'T42', descricao: 'Envenenamento por antiepilépticos, sedativos-hipnóticos e antiparkinsonianos', categoria: 'Envenenamentos' },
  { codigo: 'T43', descricao: 'Envenenamento por psicotrópicos não classificados em outra parte', categoria: 'Envenenamentos' },
  { codigo: 'T45', descricao: 'Envenenamento por substâncias farmacológicas e biológicas principalmente sistêmicas e hematológicas', categoria: 'Envenenamentos' },
  { codigo: 'T46', descricao: 'Envenenamento por substâncias que atuam primariamente sobre o aparelho cardiovascular', categoria: 'Envenenamentos' },
  { codigo: 'T47', descricao: 'Envenenamento por substâncias que atuam primariamente sobre o aparelho gastrointestinal', categoria: 'Envenenamentos' },
  { codigo: 'T48', descricao: 'Envenenamento por substâncias que atuam primariamente sobre os músculos lisos e esqueléticos e sobre o aparelho respiratório', categoria: 'Envenenamentos' },
  { codigo: 'T49', descricao: 'Envenenamento por substâncias tópicas que atuam primariamente sobre a pele e as membranas mucosas e por medicamentos oftalmológicos, otorrinolaringológicos e dentários', categoria: 'Envenenamentos' },
  { codigo: 'T50', descricao: 'Envenenamento por diuréticos e outras drogas, medicamentos e substâncias biológicas não especificadas', categoria: 'Envenenamentos' },
  { codigo: 'Z00', descricao: 'Exame geral e investigação de pessoas sem queixas ou diagnóstico relatado', categoria: 'Fatores de Risco' },
  { codigo: 'Z01', descricao: 'Outros exames e investigações especiais de pessoas sem queixa ou diagnóstico relatado', categoria: 'Fatores de Risco' },
  { codigo: 'Z02', descricao: 'Exame médico e consulta com finalidades administrativas', categoria: 'Fatores de Risco' },
  { codigo: 'Z03', descricao: 'Observação por suspeita de doenças e afecções', categoria: 'Fatores de Risco' },
  { codigo: 'Z04', descricao: 'Exame e observação por outras razões', categoria: 'Fatores de Risco' },
  { codigo: 'Z08', descricao: 'Exame de seguimento após tratamento de neoplasia maligna', categoria: 'Fatores de Risco' },
  { codigo: 'Z09', descricao: 'Exame de seguimento após tratamento de outras afecções', categoria: 'Fatores de Risco' },
  { codigo: 'Z11', descricao: 'Exame de rastreamento de doenças infecciosas e parasitárias', categoria: 'Fatores de Risco' },
  { codigo: 'Z12', descricao: 'Exame de rastreamento de neoplasias', categoria: 'Fatores de Risco' },
  { codigo: 'Z13', descricao: 'Exame de rastreamento de outros transtornos e doenças', categoria: 'Fatores de Risco' },
  { codigo: 'Z20', descricao: 'Contato com e exposição a doenças transmissíveis', categoria: 'Fatores de Risco' },
  { codigo: 'Z21', descricao: 'Estado de infecção assintomática pelo vírus da imunodeficiência humana [HIV]', categoria: 'Fatores de Risco' },
  { codigo: 'Z22', descricao: 'Portador de doença infecciosa', categoria: 'Fatores de Risco' },
  { codigo: 'Z23', descricao: 'Necessidade de imunização contra uma única doença bacteriana', categoria: 'Fatores de Risco' },
  { codigo: 'Z24', descricao: 'Necessidade de imunização contra algumas doenças virais únicas', categoria: 'Fatores de Risco' },
  { codigo: 'Z25', descricao: 'Necessidade de imunização contra outras doenças virais únicas', categoria: 'Fatores de Risco' },
  { codigo: 'Z26', descricao: 'Necessidade de imunização contra outras doenças infecciosas únicas', categoria: 'Fatores de Risco' },
  { codigo: 'Z27', descricao: 'Necessidade de imunização contra combinações de doenças infecciosas', categoria: 'Fatores de Risco' },
  { codigo: 'Z28', descricao: 'Imunização não realizada', categoria: 'Fatores de Risco' },
  { codigo: 'Z29', descricao: 'Necessidade de outras medidas profiláticas', categoria: 'Fatores de Risco' },
  { codigo: 'Z30', descricao: 'Atenção à contracepção', categoria: 'Fatores de Risco' },
  { codigo: 'Z31', descricao: 'Atenção à procriação', categoria: 'Fatores de Risco' },
  { codigo: 'Z32', descricao: 'Exame e teste de gravidez', categoria: 'Fatores de Risco' },
  { codigo: 'Z33', descricao: 'Gravidez como achado casual', categoria: 'Fatores de Risco' },
  { codigo: 'Z34', descricao: 'Supervisão de gravidez normal', categoria: 'Fatores de Risco' },
  { codigo: 'Z35', descricao: 'Supervisão de gravidez de alto risco', categoria: 'Fatores de Risco' },
  { codigo: 'Z36', descricao: 'Rastreamento pré-natal', categoria: 'Fatores de Risco' },
  { codigo: 'Z37', descricao: 'Resultado do parto', categoria: 'Fatores de Risco' },
  { codigo: 'Z38', descricao: 'Nascidos vivos segundo o lugar de nascimento', categoria: 'Fatores de Risco' },
  { codigo: 'Z39', descricao: 'Atenção e exame pós-natal', categoria: 'Fatores de Risco' },
  { codigo: 'Z40', descricao: 'Cirurgia profilática', categoria: 'Fatores de Risco' },
  { codigo: 'Z41', descricao: 'Procedimentos para outros propósitos que não melhoria do estado de saúde', categoria: 'Fatores de Risco' },
  { codigo: 'Z42', descricao: 'Seguimento envolvendo enxerto ou prótese', categoria: 'Fatores de Risco' },
  { codigo: 'Z43', descricao: 'Atenção a aberturas artificiais', categoria: 'Fatores de Risco' },
  { codigo: 'Z44', descricao: 'Atenção a aparelhos de prótese externa', categoria: 'Fatores de Risco' },
  { codigo: 'Z45', descricao: 'Ajuste e manejo de dispositivo implantado', categoria: 'Fatores de Risco' },
  { codigo: 'Z46', descricao: 'Ajuste e ajuste de outros aparelhos', categoria: 'Fatores de Risco' },
  { codigo: 'Z47', descricao: 'Outros cuidados de seguimento ortopédico', categoria: 'Fatores de Risco' },
  { codigo: 'Z48', descricao: 'Outros cuidados de seguimento cirúrgico', categoria: 'Fatores de Risco' },
  { codigo: 'Z49', descricao: 'Atenção envolvendo diálise', categoria: 'Fatores de Risco' },
  { codigo: 'Z50', descricao: 'Cuidados envolvendo uso de procedimentos de reabilitação', categoria: 'Fatores de Risco' },
  { codigo: 'Z51', descricao: 'Outros cuidados médicos', categoria: 'Fatores de Risco' },
  { codigo: 'Z52', descricao: 'Doadores de órgãos e tecidos', categoria: 'Fatores de Risco' },
  { codigo: 'Z53', descricao: 'Pessoas em contato com serviços de saúde para procedimentos específicos não realizados', categoria: 'Fatores de Risco' },
  { codigo: 'Z54', descricao: 'Convalescença', categoria: 'Fatores de Risco' },
  { codigo: 'Z55', descricao: 'Problemas relacionados com educação e alfabetização', categoria: 'Fatores de Risco' },
  { codigo: 'Z56', descricao: 'Problemas relacionados com o emprego e o desemprego', categoria: 'Fatores de Risco' },
  { codigo: 'Z57', descricao: 'Exposição ocupacional a fatores de risco', categoria: 'Fatores de Risco' },
  { codigo: 'Z58', descricao: 'Problemas relacionados com o ambiente físico', categoria: 'Fatores de Risco' },
  { codigo: 'Z59', descricao: 'Problemas relacionados com habitação e condições econômicas', categoria: 'Fatores de Risco' },
  { codigo: 'Z60', descricao: 'Problemas relacionados com o ambiente social', categoria: 'Fatores de Risco' },
  { codigo: 'Z61', descricao: 'Problemas relacionados com eventos negativos na infância', categoria: 'Fatores de Risco' },
  { codigo: 'Z62', descricao: 'Outros problemas relacionados com a educação e a criação', categoria: 'Fatores de Risco' },
  { codigo: 'Z63', descricao: 'Outros problemas relacionados com o grupo primário de apoio, inclusive a família', categoria: 'Fatores de Risco' },
  { codigo: 'Z64', descricao: 'Problemas relacionados com algumas circunstâncias psicossociais', categoria: 'Fatores de Risco' },
  { codigo: 'Z65', descricao: 'Problemas relacionados com outras circunstâncias psicossociais', categoria: 'Fatores de Risco' },
  { codigo: 'Z73', descricao: 'Problemas relacionados com dificuldades na manutenção do estilo de vida', categoria: 'Fatores de Risco' },
  { codigo: 'Z74', descricao: 'Problemas relacionados com dependência de uma pessoa que oferece cuidados à saúde', categoria: 'Fatores de Risco' },
  { codigo: 'Z75', descricao: 'Problemas relacionados com facilidades médicas e outros cuidados à saúde', categoria: 'Fatores de Risco' },
  { codigo: 'Z76', descricao: 'Pessoas em contato com serviços de saúde em outras circunstâncias', categoria: 'Fatores de Risco' },
  { codigo: 'Z80', descricao: 'História familiar de neoplasia maligna', categoria: 'Fatores de Risco' },
  { codigo: 'Z81', descricao: 'História familiar de transtornos mentais e comportamentais', categoria: 'Fatores de Risco' },
  { codigo: 'Z82', descricao: 'História familiar de algumas incapacidades e doenças crônicas que conduzem à incapacitação', categoria: 'Fatores de Risco' },
  { codigo: 'Z83', descricao: 'História familiar de outros transtornos específicos', categoria: 'Fatores de Risco' },
  { codigo: 'Z84', descricao: 'História familiar de outras afecções', categoria: 'Fatores de Risco' },
  { codigo: 'Z85', descricao: 'História pessoal de neoplasia maligna', categoria: 'Fatores de Risco' },
  { codigo: 'Z86', descricao: 'História pessoal de algumas outras doenças', categoria: 'Fatores de Risco' },
  { codigo: 'Z87', descricao: 'História pessoal de outras doenças e afecções', categoria: 'Fatores de Risco' },
  { codigo: 'Z88', descricao: 'História pessoal de alergia a drogas, medicamentos e substâncias biológicas', categoria: 'Fatores de Risco' },
  { codigo: 'Z89', descricao: 'Ausência adquirida de membros', categoria: 'Fatores de Risco' },
  { codigo: 'Z90', descricao: 'Ausência adquirida de órgãos não classificados em outra parte', categoria: 'Fatores de Risco' },
  { codigo: 'Z91', descricao: 'História pessoal de fatores de risco não classificados em outra parte', categoria: 'Fatores de Risco' },
  { codigo: 'Z92', descricao: 'História pessoal de tratamento médico', categoria: 'Fatores de Risco' },
  { codigo: 'Z93', descricao: 'Aberturas artificiais', categoria: 'Fatores de Risco' },
  { codigo: 'Z94', descricao: 'Órgãos e tecidos transplantados', categoria: 'Fatores de Risco' },
  { codigo: 'Z95', descricao: 'Presença de implantes e enxertos cardíacos e vasculares', categoria: 'Fatores de Risco' },
  { codigo: 'Z96', descricao: 'Presença de outros implantes funcionais', categoria: 'Fatores de Risco' },
  { codigo: 'Z97', descricao: 'Presença de outros dispositivos', categoria: 'Fatores de Risco' },
  { codigo: 'Z98', descricao: 'Outros estados pós-cirúrgicos', categoria: 'Fatores de Risco' },
  { codigo: 'Z99', descricao: 'Dependência de máquinas e dispositivos capacitantes não classificados em outra parte', categoria: 'Fatores de Risco' },
];

export const cid10Service = {
  search: (query: string): CID10[] => {
    if (!query || query.length < 1) return [];
    const upperQuery = query.toUpperCase();
    return cid10Table.filter(c =>
      c.codigo.includes(upperQuery) ||
      c.descricao.toUpperCase().includes(upperQuery) ||
      c.categoria.toUpperCase().includes(upperQuery)
    ).slice(0, 20);
  },

  getByCode: (codigo: string): CID10 | undefined => {
    return cid10Table.find(c => c.codigo === codigo);
  },

  getAll: (): CID10[] => {
    return [...cid10Table];
  }
};

